-- Nodo KNIME : P&G_COCO\RECOBROS (#230)\DB SQL Executor (#181)
-- Clave      : statement

USE Liberty_Pruebas_Actuaria


declare
@periodo_contable varchar(6)=$${Speriodo_contable}$$


if OBJECT_ID('tempdb.dbo.#recobros_As400','U') is not null drop table #recobros_As400

SELECT 
	DTPEKN	AS  PERIODO_CONTABLE
	,CAST(CAST(T01.DTFCPO AS VARCHAR (8)) AS DATE) AS FEC_LEGALIZADO    
	,T01.DTC9NU AS CUPON               
	,T01.DTIGNU AS NRO_INGRESO        
	,T01.DTTNNU AS TRANSACCION         
	,T01.DTCASK AS CIA                 
	,T01.DTRACG AS RAMO_PROD                
	,T01.DTANSN AS ANO_SINIESTRO       
	,T01.DTSCLD AS SUCURSAL_PROD
	,T01.DTRCNU AS NRO_SINIESTRO 
	,T01.DTPZNU AS POLIZA              
	,T01.DTDCNU AS DOCUMENTO           
	,T01.DTCTNU AS CERTIFICADO         
	,T01.DTITCG AS INTERMEDIARIO_LIDE
	,T01.DTVRPO AS VLR_PAGADO_REC            
	,CAST(CAST(T02.YAFCSN AS VARCHAR (8)) AS DATE) AS FECHA_SINIESTRO
	,T03.SBU        
into #recobros_As400
FROM [LIBERTY].[AS400].[REFIGVDT] T01
LEFT JOIN [Liberty].[AS400].[SNFSINIE] T02 ON  (T01.DTRACG = T02.YARACG AND T01.DTANSN = T02.YAANSN AND T01.DTSCLD = T02.YASCPR AND T01.DTRCNU = T02.YARCNU)
LEFT JOIN [Liberty].[APOYO].[DWH_SBU_RAMO_PROD] T03 ON TRIM(T01.DTRACG) = TRIM(T03.RAMO_PROD)
WHERE DTTNNU = 31
AND DTPEKN = @PERIODO_CONTABLE
