-- Nodo KNIME : P&G_COCO\SALVAMENTOS (#229)\DB SQL Executor (#181)
-- Clave      : statement

USE Liberty_Pruebas_Actuaria


declare
@periodo_contable varchar(6)=$${Speriodo_contable}$$


if OBJECT_ID('tempdb.dbo.#salvamentos_As400','U') is not null drop table #salvamentos_as400

select 
DTPEKN	AS  PERIODO_CONTABLE
,DTSCNU AS  SUCURSAL_INGRESO
,DTSCLD	as  SUCURSAL_PROD
,DTRACG AS 	RAMO_PROD
,DTPZNU AS	POLIZA
,DTCTNU AS	CERTIFICADO
,DTDCNU AS	DOCUMENTO
,DTANSN AS	ANO_SINIESTRO
,DTRCNU AS	NRO_RADC_SINIESTRO
,DTTDNT AS  NIT_TOMADOR
,DTASNT AS	NIT_ASEGURADO
,DTITCG AS	INTERMEDIARIO_LIDE
,DTVRPO AS	VLR_PAGADO_SAL
,DTIVAC AS  VALOR_IVA_COMISION
,DTIVRC AS	VALOR_IVA_RETENIDO
,DTINDC AS	VALOR_INDUS_CIO
,DTRTEF AS	VALOR_RTE_FTE
,DTIBOM AS	VR_IMP_BOMBERIL
,DTFCPO AS	FEC_LEGALIZADO
into #salvamentos_As400
from liberty.[AS400].[REFIGVDT]
where DTPEKN = @PERIODO_CONTABLE AND DTTNNU IN (30)--, 143, 153, 142)
